Fill unused field for shape stability of PlainResult type with `null` instead of `undefined`
This is just **Breaking Change**.

Motivation
----

With Next.js v12.1, we cannot use `PlainResult` type as the returned type for `getServerSideProps()` by following error.

```
Server Error

Error: Error serializing `.val` returned from `getServerSideProps` in "/path/[bafoo]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

To avoid this error, an user need to re-implement `createOk`/`createErr`.

Next.js is emerging web development framework and I think it's important for next 3~5 years.

So we should fix them.

Possible Performance Impact
---

I confirmed what this change impacts on JSVM's internal shape (SM)/hidden class (V8)/structure (JSC).
I tested JavaScriptCore (for Safari 15.4), SpiderMonkey (for Firefox v99), and V8 9.9.
They are now used a single shape.

So I conclude this would cause a serious performance problem.